// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahebihagwajrdbgzmmib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZWJpaGFnd2FqcmRiZ3ptbWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Nzc3NDcsImV4cCI6MjA1OTA1Mzc0N30.lDo0TEwOEz5BSI3UVmUExz8Jf3HG1kLU7rztXXRp_mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);